[book]
authors = ["Zachary Kohnen"]
language = "en"
multilingual = false
src = "src"
title = "ECS Notes"

[build]
create-missing = false

[output.html]
default-theme = "navy"
cname = "ecs-notes.dusterthefirst.com"
git-repository-url = "https://github.com/DusterTheFirst/ecs-notes"
google-analytics = "G-3S02PN40BH"

[output.linkcheck]