[book]
authors = ["Zachary Kohnen"]
language = "en"
multilingual = false
src = "src"
title = "ECS Notes"

[build]

[output.html]
default-theme = "navy"
cname = "ecs-notes.dusterthefirst.com"
git-repository-url = "https://github.com/DusterTheFirst/ecs-notes"
google-analytics = "UA-107070534-2"

[output.linkcheck]