name: Build mdBook
on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Install mdbook-linkcheck
        run: |
          curl -LSfs https://japaric.github.io/trust/install.sh | \
            sh -s -- --git Michael-F-Bryan/mdbook-linkcheck

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
          publish_branch: rendered
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install markdownlint-cli2
        run: yarn global add markdownlint-cli2

      - name: Run markdownlint-cli2
        run: $(yarn global bin)markdownlint-cli2 **/*.md